name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: determine version number
        run: ./github_env.sh
        env:
          GITHUB_RELEASE_TAG: ${{ github.event.release.tag_name }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username dummy --password-stdin
      - name: Build the Docker image
        env:
          GIT_AUTHOR_NAME: ${{ github.event.head_commit.author.name }}
        run: docker buildx build .
          --file Dockerfile.bullseye
          --label org.opencontainers.image.created="$(date +'%Y-%m-%dT%H:%M:%S%z')"
          --label org.opencontainers.image.authors="$GIT_AUTHOR_NAME <tierleben-development@vkb.de>"
          --label org.opencontainers.image.source="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
          --label org.opencontainers.image.revision="$GITHUB_SHA"
          --label org.opencontainers.image.url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          --tag ghcr.io/$GITHUB_REPOSITORY/${GITHUB_REPOSITORY#*/}:$BUILD_VERSION
          --tag ghcr.io/$GITHUB_REPOSITORY/${GITHUB_REPOSITORY#*/}:$TAG_NAME
          --platform=linux/amd64,linux/arm64
          --push
